######################################################
version: '2.1'
services:

# AIRFLOW
######################################################

  airflow:
    build: ./airflow
    restart: always
    container_name: msfAlerta
    volumes:
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./airflow/dags:/opt/airflow/dags





    ports:
      - 8081:8081
    healthcheck:
      test: [ "CMD", "nc", "-z", "airflow", "8081" ]
      timeout: 45s
      interval: 10s
      retries: 10
